development:
  adapter: postgresql
  encoding: utf8
  database: errbit_development
  host: localhost
  min_messages: WARNING
  prepared_statements: false

test:
  adapter: postgresql
  encoding: utf8
  database: errbit_test
  host: localhost
  min_messages: WARNING
  prepared_statements: false
